[book]
authors = ["Jerry"]
language = "en"
multilingual = false
src = "src"
title = "History Notes"

[preprocessor.mermaid]
command = "mdbook-mermaid"
renderer = ["html"]

[output.html]
additional-css = ["mermaid.css"]
additional-js = ["mermaid.min.js", "mermaid-init.js"]